name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '**/*.docc/**'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    timeout-minutes: 30
    runs-on: macOS-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.4.app
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=macOS,variant=Mac Catalyst"
          - "platform=iOS Simulator,name=iPhone 16"
          - "platform=tvOS Simulator,name=Apple TV"
          - "platform=watchOS Simulator,name=Apple Watch Series 10 (42mm)"
          - "platform=visionOS Simulator,name=Apple Vision Pro,OS=2.5"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme SwiftTreeSitter -destination "${{ matrix.destination }}" test | xcbeautify

  linux_test:
    name: Test Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Swiftly
        uses: vapor/swiftly-action@v0.2.0
        with:
          toolchain: 6.1.0
      - name: Test
        run: swift test
